[package]
name = "wordcrab"
version = "0.10.2"
authors = ["Walther <veeti.haapsamo@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A command-line tool for counting lines, words and characters in documents."
repository = "https://github.com/Walther/wordcrab"
categories = ["command-line-utilities"]
readme = "README.md"

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "Walther/wordcrab", branch = "master" }
codecov = { repository = "Walther/wordcrab", branch = "master", service = "github" }


[dependencies]
structopt = "0.3.5"
clap = "2.33.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
serde_yaml = "0.8.11"
rayon = "1.2.1"

[profile.release]
lto = true
